{% set name = "elfi" %}
{% set version = "0.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/elfi-dev/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: f22db5c444645aa1eaa166c34d46d49b6c5f2d884126997f92d5267a690f7af5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3
    - pip

  run:
    - python >=3
    - numpy
    - scipy >=0.19
    - matplotlib-base
    - GPy
    - networkX >=2.0
    - ipyparallel
    - toolz
    - scikit-learn
    - graphviz
    - dask[distributed] >=2.30.0
    - numdifftools

test:
  imports:
    - elfi

about:
  home: http://www.elfi.ai/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ELFI - Engine for Likelihood-Free Inference
  description: |
    ELFI is a statistical software package written in Python for likelihood-free
    inference (LFI) such as Approximate Bayesian Computation (ABC).
  dev_url: https://github.com/elfi-dev/elfi

extra:
  recipe-maintainers:
    - johnlees
    - hpesonen
