travis:
  secure:
    BINSTAR_TOKEN: py9mJIIXI/ZN1pA5VaP7+mtIkgHITHJfDLg0/znyzdAmt5fSrmI4bymS2ohoCEyEz6l99toXYGKUn7ikTqeX/rXDofvpUny8HXRGNg4JIPZDsevnl6XaIta2aMDY7YEIFvPIHxbwYIlsQl01dTFwrkYHsdmKvtRxh3IOOpUO8X+3jNnXwfppfyhxk8JT8/g3JLzY7RqWBzPa6K4NXbcj8XASuqFI/+DDaQb7Tvlraqy8aLLJTyzLJh29Z2d1ND41Xr2fVpFC8+4Xpc1K8Xyd537IsG/du6ztvZ7DVcPEfztUIqOzIYNOOndiNtJhTAcAmLMnshDkWHIBNjafZ9YIr5dwW+z2wjWxaZechpaSO0iIjrP+O/ETP6gs/TR55qOuY1/bytnEyiXGlswFSJ3+SUpbr4+Xn2z1+Og8wcBljvT++7+6yCwUjVs6Bln7vdlvTube/WhAHifAz+lx4KgicF+EXlp2xpuWYLmz5QdXMu+7XsYKyAe+MGsK/GAqR4uKtXh0DiknrUmfnhxmGvrd/Ga/rtTuQYMU6eX7wGG1r3xLaUDoRM/b+RPmVkgg4OcygYzcVJEeWUOzZFeCDd8Hzg1yD2YOnkLQtPtI+chUiqXAwR05s2yCttwHsFPQwcxKl0O5sr+AmBzmviIKJYZN/SMXt6y5xRURJQ9poINv1Hg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
