travis:
  secure:
    BINSTAR_TOKEN: qf5jT8KzLi4vo+l3f3V4WWrTe6/SqtOxZb+hxXrJvTVYpX6ggbtuROyEIAv8Kl0LB60kqIPSsX7GseyCyodufG5qpWlPHZ5Yok3kFd78lwAgz+EVpvtNzi5PteAV+lq/6/f7P9JaihMd1IXfiJUwaS1JLFU5zeYIYE5IATP5tT5gDGPXwgLaOpHgoY9RRMttACvde0bqQv6kGHogywx4lsQzCA0nF5gX2NbDMeBysLtD2I4tOUqFPCoxcASVNBV+oNTH2FAbqGDJ0XHNyaaYGuSvKlMwmhaiMnZaaTwLifa9ARS0LQqHeCM4QV9AiFdSDqU9sRy6SoS8YVK54potMyJ8zu2XEt8LEn/JVRNpBYU2vEIt/gmhNW7e6pgpjv4pr3qrcvVgATNKFP9hGXU9bxYQ9t6fnR4RuUh0zHfjyJpvDiv3r85UZ2TMPFyxljpQSSce8zGPJhjMCukimJDiCF3Hm0CYqJS7iRkejTylrAeXg5dMbOmvo5uhTqtUX1Gk72+nIahJgmFyWWO6Y3v4GJ1mFO8NGqTU3WNshxVsXweS1mXcrOudd6bpWyRrqEwxEILDaWCqfD+ajqYQtS5FCITG73xFi32QZDW5IEbzMqiCJwH5hAzwTMLaVKxt7BjjKDPko+yOqqNeYhKASwTkBJJLqQsUDQjU7Vz56b2tUr0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
